/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllData {
  'contact' : [] | [ContactSettings],
  'reviews' : Array<Review>,
  'projects' : Array<Project>,
  'educations' : Array<Education>,
  'dailyVisits' : Array<[string, bigint]>,
  'totalVisits' : bigint,
  'experiences' : Array<Experience>,
  'skills' : Array<SkillCategory>,
  'profile' : [] | [ProfileSettings],
}
export interface ContactSettings {
  'behanceUrl' : string,
  'instagramUrl' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
  'linkedinUrl' : string,
}
export interface Education {
  'id' : string,
  'sortOrder' : bigint,
  'year' : string,
  'degree' : string,
  'college' : string,
}
export interface Experience {
  'id' : string,
  'title' : string,
  'period' : string,
  'sortOrder' : bigint,
  'description' : string,
  'company' : string,
}
export interface ProfileSettings {
  'tagline' : string,
  'name' : string,
  'greeting' : string,
  'jobTitle' : string,
  'profilePhotoUrl' : string,
  'resumeFileName' : string,
  'resumeUrl' : string,
}
export interface Project {
  'id' : string,
  'url' : string,
  'title' : string,
  'sortOrder' : bigint,
  'imageUrl' : string,
}
export interface Review {
  'id' : string,
  'name' : string,
  'role' : string,
  'reviewText' : string,
  'company' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface SkillCategory {
  'id' : string,
  'sortOrder' : bigint,
  'category' : string,
  'items' : Array<string>,
}
export interface _SERVICE {
  'addEducation' : ActorMethod<[string, Education], boolean>,
  'addExperience' : ActorMethod<[string, Experience], boolean>,
  'addProject' : ActorMethod<[string, Project], boolean>,
  'addSkillCategory' : ActorMethod<[string, SkillCategory], boolean>,
  'deleteEducation' : ActorMethod<[string, string], boolean>,
  'deleteExperience' : ActorMethod<[string, string], boolean>,
  'deleteProject' : ActorMethod<[string, string], boolean>,
  'deleteReview' : ActorMethod<[string, string], boolean>,
  'deleteSkillCategory' : ActorMethod<[string, string], boolean>,
  'getAllData' : ActorMethod<[], AllData>,
  'getContactSettings' : ActorMethod<[], [] | [ContactSettings]>,
  'getDailyVisits' : ActorMethod<[], Array<[string, bigint]>>,
  'getEducations' : ActorMethod<[], Array<Education>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getProfileSettings' : ActorMethod<[], [] | [ProfileSettings]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getReviewCount' : ActorMethod<[], bigint>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getSkills' : ActorMethod<[], Array<SkillCategory>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'recordVisit' : ActorMethod<[], undefined>,
  'setAdminPin' : ActorMethod<[string, string], boolean>,
  'setContactSettings' : ActorMethod<[string, ContactSettings], boolean>,
  'setProfileSettings' : ActorMethod<[string, ProfileSettings], boolean>,
  'submitReview' : ActorMethod<[Review], boolean>,
  'updateEducation' : ActorMethod<[string, string, Education], boolean>,
  'updateExperience' : ActorMethod<[string, string, Experience], boolean>,
  'updateProject' : ActorMethod<[string, string, Project], boolean>,
  'updateSkillCategory' : ActorMethod<[string, string, SkillCategory], boolean>,
  'verifyAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];