/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'reviewText' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteReview' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getDailyVisits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
  'getReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'recordVisit' : IDL.Func([IDL.Text], [], []),
  'setAdminPin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'verifyAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'reviewText' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteReview' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getDailyVisits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
    'getReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getTotalVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'recordVisit' : IDL.Func([IDL.Text], [], []),
    'setAdminPin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'verifyAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };