/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Review {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'reviewText' : string,
  'company' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface _SERVICE {
  'deleteReview' : ActorMethod<[string, bigint], boolean>,
  'getDailyVisits' : ActorMethod<[], Array<[string, bigint]>>,
  'getReview' : ActorMethod<[bigint], Review>,
  'getReviewCount' : ActorMethod<[], bigint>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'recordVisit' : ActorMethod<[string], undefined>,
  'setAdminPin' : ActorMethod<[string, string], boolean>,
  'submitReview' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'verifyAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];