/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Experience {
  'id' : bigint,
  'title' : string,
  'period' : string,
  'sortOrder' : bigint,
  'description' : string,
  'company' : string,
}
export interface Project {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'sortOrder' : bigint,
  'imageUrl' : string,
}
export interface Review {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'reviewText' : string,
  'company' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface SkillCategory {
  'id' : bigint,
  'sortOrder' : bigint,
  'category' : string,
  'items' : Array<string>,
}
export interface VisitRecord { 'date' : string, 'count' : bigint }
export interface _SERVICE {
  'addExperience' : ActorMethod<
    [string, string, string, string, string, bigint],
    bigint
  >,
  'addProject' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addSkillCategory' : ActorMethod<
    [string, string, Array<string>, bigint],
    bigint
  >,
  'deleteExperience' : ActorMethod<[string, bigint], boolean>,
  'deleteProject' : ActorMethod<[string, bigint], boolean>,
  'deleteReview' : ActorMethod<[string, bigint], boolean>,
  'deleteSkillCategory' : ActorMethod<[string, bigint], boolean>,
  'getAllData' : ActorMethod<
    [],
    {
      'reviews' : Array<Review>,
      'projects' : Array<Project>,
      'dailyVisits' : Array<VisitRecord>,
      'totalVisits' : bigint,
      'experiences' : Array<Experience>,
      'skills' : Array<SkillCategory>,
    }
  >,
  'getDailyVisits' : ActorMethod<[], Array<VisitRecord>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getReview' : ActorMethod<[bigint], Review>,
  'getReviewCount' : ActorMethod<[], bigint>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getSkills' : ActorMethod<[], Array<SkillCategory>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'recordVisit' : ActorMethod<[string], undefined>,
  'setAdminPin' : ActorMethod<[string, string], boolean>,
  'submitReview' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'updateExperience' : ActorMethod<
    [string, bigint, string, string, string, string, bigint],
    boolean
  >,
  'updateProject' : ActorMethod<
    [string, bigint, string, string, string, bigint],
    boolean
  >,
  'verifyAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];