/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactSettings {
    behanceUrl: string;
    instagramUrl: string;
    email: string;
    phone: string;
    location: string;
    linkedinUrl: string;
}
export interface Experience {
    id: string;
    title: string;
    period: string;
    sortOrder: bigint;
    description: string;
    company: string;
}
export interface Education {
    id: string;
    sortOrder: bigint;
    year: string;
    degree: string;
    college: string;
}
export interface AllData {
    contact?: ContactSettings;
    reviews: Array<Review>;
    projects: Array<Project>;
    educations: Array<Education>;
    dailyVisits: Array<[string, bigint]>;
    totalVisits: bigint;
    experiences: Array<Experience>;
    skills: Array<SkillCategory>;
    profile?: ProfileSettings;
}
export interface SkillCategory {
    id: string;
    sortOrder: bigint;
    category: string;
    items: Array<string>;
}
export interface Project {
    id: string;
    url: string;
    title: string;
    sortOrder: bigint;
    imageUrl: string;
}
export interface Review {
    id: string;
    name: string;
    role: string;
    reviewText: string;
    company: string;
    timestamp: bigint;
    rating: bigint;
}
export interface ProfileSettings {
    tagline: string;
    name: string;
    greeting: string;
    jobTitle: string;
    profilePhotoUrl: string;
    resumeFileName: string;
    resumeUrl: string;
}
export interface backendInterface {
    addEducation(pin: string, edu: Education): Promise<boolean>;
    addExperience(pin: string, exp: Experience): Promise<boolean>;
    addProject(pin: string, proj: Project): Promise<boolean>;
    addSkillCategory(pin: string, cat: SkillCategory): Promise<boolean>;
    deleteEducation(pin: string, id: string): Promise<boolean>;
    deleteExperience(pin: string, id: string): Promise<boolean>;
    deleteProject(pin: string, id: string): Promise<boolean>;
    deleteReview(pin: string, id: string): Promise<boolean>;
    deleteSkillCategory(pin: string, id: string): Promise<boolean>;
    getAllData(): Promise<AllData>;
    getContactSettings(): Promise<ContactSettings | null>;
    getDailyVisits(): Promise<Array<[string, bigint]>>;
    getEducations(): Promise<Array<Education>>;
    getExperiences(): Promise<Array<Experience>>;
    getProfileSettings(): Promise<ProfileSettings | null>;
    getProjects(): Promise<Array<Project>>;
    getReviewCount(): Promise<bigint>;
    getReviews(): Promise<Array<Review>>;
    getSkills(): Promise<Array<SkillCategory>>;
    getTotalVisits(): Promise<bigint>;
    recordVisit(): Promise<void>;
    setAdminPin(currentPin: string, newPin: string): Promise<boolean>;
    setContactSettings(pin: string, settings: ContactSettings): Promise<boolean>;
    setProfileSettings(pin: string, settings: ProfileSettings): Promise<boolean>;
    submitReview(review: Review): Promise<boolean>;
    updateEducation(pin: string, id: string, edu: Education): Promise<boolean>;
    updateExperience(pin: string, id: string, exp: Experience): Promise<boolean>;
    updateProject(pin: string, id: string, proj: Project): Promise<boolean>;
    updateSkillCategory(pin: string, id: string, cat: SkillCategory): Promise<boolean>;
    verifyAdmin(pin: string): Promise<boolean>;
}
import type { AllData as _AllData, ContactSettings as _ContactSettings, Education as _Education, Experience as _Experience, ProfileSettings as _ProfileSettings, Project as _Project, Review as _Review, SkillCategory as _SkillCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEducation(arg0: string, arg1: Education): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducation(arg0, arg1);
            return result;
        }
    }
    async addExperience(arg0: string, arg1: Experience): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1);
            return result;
        }
    }
    async addProject(arg0: string, arg1: Project): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1);
            return result;
        }
    }
    async addSkillCategory(arg0: string, arg1: SkillCategory): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkillCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkillCategory(arg0, arg1);
            return result;
        }
    }
    async deleteEducation(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEducation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEducation(arg0, arg1);
            return result;
        }
    }
    async deleteExperience(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0, arg1);
            return result;
        }
    }
    async deleteReview(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0, arg1);
            return result;
        }
    }
    async deleteSkillCategory(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkillCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkillCategory(arg0, arg1);
            return result;
        }
    }
    async getAllData(): Promise<AllData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllData();
                return from_candid_AllData_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllData();
            return from_candid_AllData_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSettings(): Promise<ContactSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSettings();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSettings();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyVisits(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyVisits();
            return result;
        }
    }
    async getEducations(): Promise<Array<Education>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducations();
            return result;
        }
    }
    async getExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiences();
            return result;
        }
    }
    async getProfileSettings(): Promise<ProfileSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileSettings();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileSettings();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getReviewCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewCount();
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getSkills(): Promise<Array<SkillCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkills();
            return result;
        }
    }
    async getTotalVisits(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVisits();
            return result;
        }
    }
    async recordVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit();
            return result;
        }
    }
    async setAdminPin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPin(arg0, arg1);
            return result;
        }
    }
    async setContactSettings(arg0: string, arg1: ContactSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactSettings(arg0, arg1);
            return result;
        }
    }
    async setProfileSettings(arg0: string, arg1: ProfileSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfileSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfileSettings(arg0, arg1);
            return result;
        }
    }
    async submitReview(arg0: Review): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async updateEducation(arg0: string, arg1: string, arg2: Education): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEducation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEducation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateExperience(arg0: string, arg1: string, arg2: Experience): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProject(arg0: string, arg1: string, arg2: Project): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSkillCategory(arg0: string, arg1: string, arg2: SkillCategory): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkillCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkillCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdmin(arg0);
            return result;
        }
    }
}
function from_candid_AllData_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllData): AllData {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactSettings]): ContactSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileSettings]): ProfileSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: [] | [_ContactSettings];
    reviews: Array<_Review>;
    projects: Array<_Project>;
    educations: Array<_Education>;
    dailyVisits: Array<[string, bigint]>;
    totalVisits: bigint;
    experiences: Array<_Experience>;
    skills: Array<_SkillCategory>;
    profile: [] | [_ProfileSettings];
}): {
    contact?: ContactSettings;
    reviews: Array<Review>;
    projects: Array<Project>;
    educations: Array<Education>;
    dailyVisits: Array<[string, bigint]>;
    totalVisits: bigint;
    experiences: Array<Experience>;
    skills: Array<SkillCategory>;
    profile?: ProfileSettings;
} {
    return {
        contact: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.contact)),
        reviews: value.reviews,
        projects: value.projects,
        educations: value.educations,
        dailyVisits: value.dailyVisits,
        totalVisits: value.totalVisits,
        experiences: value.experiences,
        skills: value.skills,
        profile: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.profile))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
